<%@ Page Title="" Language="C#" MasterPageFile="~/index.Master" AutoEventWireup="true" CodeBehind="home.aspx.cs" Inherits="sujanChaudhary19033605.home" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style2 {
            color: rgb(255, 204, 0);
        }
        .auto-style3 {
            color: rgb(51, 51, 153);
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="text-center" style="box-sizing: border-box; text-align: center !important; color: rgb(33, 37, 41); font-family: &quot;Roboto Slab&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 249, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h1 class="text-left" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1.5rem !important; font-weight: 600; line-height: 1.2; font-size: 56px; font-family: Raleway, sans-serif; margin-right: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px !important; padding-left: 0px; color: rgb(255, 255, 255); text-transform: uppercase; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box; color: rgb(248, 34, 73);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="box-sizing: border-box; " class="auto-style3">Welcome to</span><span style="box-sizing: border-box; color: rgb(248, 34, 73);"> </span></h1>
        <h1 class="text-left" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1.5rem !important; font-weight: 600; line-height: 1.2; font-size: 56px; font-family: Raleway, sans-serif; margin-right: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px !important; padding-left: 0px; color: rgb(255, 255, 255); text-transform: uppercase; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box; color: rgb(248, 34, 73);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="box-sizing: border-box; " class="auto-style2">Berkeley College</span>C</h1>
        <h1 class="text-left" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1.5rem !important; font-weight: 600; line-height: 1.2; font-size: 56px; font-family: Raleway, sans-serif; margin-right: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px !important; padding-left: 0px; color: rgb(255, 255, 255); text-transform: uppercase; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ONFERENCE<asp:Image ID="Image2" runat="server" Height="520px" ImageUrl="~/Img/graduate.png" Width="572px" />
        </h1>
        <h2 class="section-heading text-uppercase" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-family: Montserrat, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-weight: 700; line-height: 1.2; font-size: 2.5rem; text-transform: uppercase !important;">OUR AMAZING TEAM</h2>
        <h3 class="section-subheading text-muted" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 4rem; font-family: &quot;Roboto Slab&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-weight: 400; line-height: 1.2; font-size: 1rem; --bs-text-opacity: 1; color: rgb(108, 117, 125) !important; font-style: italic;">None of us is smart as all of us.</h3>
    </div>
    <div class="row" style="box-sizing: border-box; --bs-gutter-x: 1.5rem; --bs-gutter-y: 0; display: flex; flex-wrap: wrap; margin-top: calc(-1 * var(--bs-gutter-y)); margin-right: calc(-0.5 * var(--bs-gutter-x)); margin-left: calc(-0.5 * var(--bs-gutter-x)); color: rgb(33, 37, 41); font-family: &quot;Roboto Slab&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(248, 249, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <div class="col-lg-4" style="box-sizing: border-box; flex: 0 0 auto; width: 439.987px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * 0.5); padding-left: calc(var(--bs-gutter-x) * 0.5); margin-top: var(--bs-gutter-y);">
            <div class="team-member" style="box-sizing: border-box; margin-bottom: 3rem; text-align: center;">
                &nbsp;
                <img alt="..." class="mx-auto rounded-circle" src="https://startbootstrap.github.io/startbootstrap-agency/assets/img/team/1.jpg" style="box-sizing: border-box; vertical-align: middle; margin-right: auto !important; margin-left: auto !important; border-radius: 50% !important; width: 14rem; height: 14rem; border: 0.5rem solid rgba(0, 0, 0, 0.1);" /><h4 style="box-sizing: border-box; margin-top: 1.5rem; margin-bottom: 0px; font-family: Montserrat, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-weight: 700; line-height: 1.2; font-size: 1.5rem;">Parveen Anand</h4>
            </div>
        </div>
        <div class="col-lg-4" style="box-sizing: border-box; flex: 0 0 auto; width: 439.987px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * 0.5); padding-left: calc(var(--bs-gutter-x) * 0.5); margin-top: var(--bs-gutter-y);">
            <div class="team-member" style="box-sizing: border-box; margin-bottom: 3rem; text-align: center;">
                <img alt="..." class="mx-auto rounded-circle" src="https://startbootstrap.github.io/startbootstrap-agency/assets/img/team/2.jpg" style="box-sizing: border-box; vertical-align: middle; margin-right: auto !important; margin-left: auto !important; border-radius: 50% !important; width: 14rem; height: 14rem; border: 0.5rem solid rgba(0, 0, 0, 0.1);" /><h4 style="box-sizing: border-box; margin-top: 1.5rem; margin-bottom: 0px; font-family: Montserrat, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-weight: 700; line-height: 1.2; font-size: 1.5rem;">Diana Petersen</h4>
            </div>
        </div>
        <div class="col-lg-4" style="box-sizing: border-box; flex: 0 0 auto; width: 439.987px; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * 0.5); padding-left: calc(var(--bs-gutter-x) * 0.5); margin-top: var(--bs-gutter-y);">
            <div class="team-member" style="box-sizing: border-box; margin-bottom: 3rem; text-align: center;">
                <img alt="..." class="mx-auto rounded-circle" src="https://startbootstrap.github.io/startbootstrap-agency/assets/img/team/3.jpg" style="box-sizing: border-box; vertical-align: middle; margin-right: auto !important; margin-left: auto !important; border-radius: 50% !important; width: 14rem; height: 14rem; border: 0.5rem solid rgba(0, 0, 0, 0.1);" /><h4 style="box-sizing: border-box; margin-top: 1.5rem; margin-bottom: 0px; font-family: Montserrat, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-weight: 700; line-height: 1.2; font-size: 1.5rem;">Larry Parker</h4>
            </div>
        </div>
    </div>
</asp:Content>
